server:
  port: 8888
  context-path: /girls

# 变量定义
name: 貂蝉
age: 200
cupSize: D

#变量properties
girl:
 name: 貂蝉
 age: 200
 cupSize: D
spring:
  profiles:
    #配置引用配置文件
    active: prod
  #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    username: root
    password: root
  #配置JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 配置视图解析器
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html




